# Generated by Django 6.0.3 on 2026-06-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agent_location_text_agent_phone_number_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='username',
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='agent_set', related_query_name='agent', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='location_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='agent_set', related_query_name='agent', to='auth.permission'),
        ),
    ]
