# Generated by Django 6.0.3 on 2026-06-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_agent_managers_remove_agent_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
