# Generated by Django 6.0.3 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agent_location_metrics'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='auth_code',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='agent_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='agent_set', to='auth.permission'),
        ),
    ]
