# Generated by Django 6.0.3 on 2026-07-05 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National Identity Card'), ('TITLE_DEED', 'Official Title Deed'), ('CONTRACT_IMAGE', 'Signed Contract Signature')], max_length=30)),
                ('file', models.FileField(upload_to='registry_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.deal')),
            ],
        ),
    ]
