# Generated by Django 6.0.3 on 2026-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PROPERTY_DEED', 'Property Deed'), ('CONTRACT_PDF', 'Contract PDF'), ('PHOTO', 'Photo'), ('COURT_ORDER', 'Court Order'), ('WITNESS_LETTER', 'Witness Letter'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
