# Generated by Django 6.0.3 on 2026-07-05 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_type', models.CharField(choices=[('RENTAL', 'Rental'), ('SALE', 'Sale'), ('MORTGAGE', 'Mortgage')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=150)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.IntegerField()),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_contract', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_file_url', models.CharField(blank=True, max_length=255)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='SaleContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('payment_method', models.CharField(max_length=100)),
                ('deed_reference_number', models.CharField(blank=True, max_length=100)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_contract', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='DealParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Property Owner'), ('BUYER', 'Buyer'), ('RENTER', 'Renter'), ('LENDER', 'Lender')], max_length=20)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_roles', to='citizens.citizen')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='deals.deal')),
            ],
            options={
                'unique_together': {('deal', 'citizen', 'role')},
            },
        ),
    ]
