# Generated by Django 6.0.3 on 2026-06-22 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_number', models.CharField(max_length=50, unique=True)),
                ('deal_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='DealParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_parties', to='citizens.citizen')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='deals.deal')),
            ],
        ),
    ]
