# Generated by Django 6.0.3 on 2026-06-22 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('step_owner_verification', models.CharField(default='PENDING', max_length=20)),
                ('step_property_verification', models.CharField(default='PENDING', max_length=20)),
                ('step_renter_verification', models.CharField(default='PENDING', max_length=20)),
                ('final_decision', models.CharField(default='NOT_DECIDED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='deals.deal')),
            ],
        ),
    ]
