# Generated by Django 6.0.3 on 2026-06-22 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
        ('properties', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealworkflow',
            name='status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='CitizenVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='citizens.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='properties.property')),
            ],
        ),
    ]
