# STATUS VALUES (GLOBAL SYSTEM RULES)

STATUS_PENDING = "PENDING"
STATUS_APPROVED = "APPROVED"
STATUS_REJECTED = "REJECTED"
STATUS_UNDER_REVIEW = "UNDER_REVIEW"


DEAL_TYPES = (
    "RENT",
    "SALE",
    "MORTGAGE",
)